name: "Epic "
description: "驻住 爪专转 驻拽 (Epic) -   专转 住驻专 砖转"
type: Epic 

body:
  - type: textarea
    id: epic_description
    attributes:
      label: "转专 驻拽"
      description: |
        <div dir="rtl">
        "转专 驻专 砖 注 注专 砖驻拽 "
        </div>
      value: |
        <div dir="auto">
        
        
        </div>
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "拽专专 砖"
      description: |
        <div dir="rtl">
        " 爪专 转拽  住 转 驻拽 砖"
        </div>
      value: |
        <div dir="auto">


        </div>
    validations:
      required: false
