name: "Spike "
description: "驻住 拽专 , 拽转 转转,  转 驻转专转"
type: "Spike "

body:
  - type: textarea
    id: spike_question
    attributes:
      label: "砖 专转"
      description: |
        <div dir="rtl">
         砖 注拽专转 砖住驻拽   注转 注?
        </div>
      value: |
        <div dir="rtl">
        
    

        </div>
    validations:
      required: false
