name: "Technical User Story ⚒️"
description: "טופס ליצירת סיפור משתמש טכני - שיפורים טכניים, ריפקטורינג, או חובות טכניים"
type: Technical Story ⚒️

body:
  - type: textarea
    id: technical_story
    attributes:
      label: "הסיפור הטכני"
      description: "תאר את הצורך הטכני בפורמט: כ[מפתח/מערכת], אני רוצה [מה], כדי ש[מדוע]"
      placeholder: "כמפתח, אני רוצה לרפקטר את שכבת הנתונים, כדי שהקוד יהיה יותר נקי וניתן לתחזוקה"
    validations:
      required: false