name: "Technical User Story ⚒️"
description: "טופס ליצירת סיפור משתמש טכני - שיפורים טכניים, ריפקטורינג, או חובות טכניים"
type: Technical Story ⚒️

body:
  - type: textarea
    id: technical_story
    attributes:
      label: "הסיפור הטכני"
      description: |
        <div dir="rtl">
        תאר את הצורך הטכני בפורמט: כ[מפתח/מערכת], אני רוצה [מה], כדי ש[מדוע]
        </div>
      value: |
        <div dir="rtl">
        
        
        </div>
    validations:
      required: false