name: "Acceptance Test Fixes И"
description: "转拽 砖 砖转 拽转 拽 专砖 住 专住"
type: "Acceptance Test Fixes И"

body:
  - type: textarea
    id: acceptance_findings
    attributes:
      label: "爪 拽转 拽"
      description: " 转 拽转 拽 砖专砖 转拽 驻 砖专专"
      placeholder: |
        - 驻爪'专 砖  注 驻驻 Safari
        -  注   住转 爪专
        - 注转 砖  专专 砖转砖 拽爪
        - 住专 validation 驻住 砖
    validations:
      required: false