name: "Acceptance Story 🔧"
description: "תיקונים ושינויים שהתגלו בבדיקות קבלה הנדרשים לסיום הגרסה"
type: "Acceptance Story 🔧"

body:
  - type: textarea
    id: acceptance_findings
    attributes:
      label: "ממצאים בבדיקות קבלה"
      description: "מה התגלה בבדיקות הקבלה שדורש תיקון לפני השחרור"
      value: |
        <div dir="rtl">
          - הפיצ'ר החדש לא עובד בדפדפן Safari
          - זמני טעינה איטיים מדי בסביבת ייצור
          - הודעת שגיאה לא ברורה למשתמש הקצה
          - חסר validation בטופס החדש
        </div>
    validations:
      required: false
  - type: input
    id: specification_link
    attributes:
      label: "קישור למסמך אפיון / מסמך עיצוב"
      description: "אם יש מסמך שמסביר איך התכונה אמורה לעבוד, הכנס כאן את הקישור"
      placeholder: "https://…"
    validations:
      required: false