name: "Release Story "
description: "专 转 拽转 拽, 转拽 专砖 爪转 专住 驻注"
type: "Release Story "

body:
  - type: markdown
    attributes:
      value: |
        <div dir="rtl">
        <h3>  砖专专 专住</h3>
        砖  转 转  转 砖专专:  拽转 拽, 专 转拽  拽专 注 驻专住 住驻转 (Deploy).
        </div>

  - type: textarea
    id: version_goals
    attributes:
      label: "注专转 砖专专"
      description: |
        <div dir="rtl">
          砖专专 砖 专住  ?
        </div>
      value: |
        <div dir="rtl">
        
        </div>
    validations:
      required: false