name: "Bug "
description: "驻住 驻砖  注 转拽  注 注专转"
type: "Bug "

body:
  - type: textarea
    id: summary
    attributes:
      label: " 注?"
      description: |
        <div dir="rtl">
        : 驻转专 砖专  注
        </div>
      value: |
        <!-- For hebrew content use this template:
        <div dir="rtl">
        
        
        </div>
        -->
    validations:
      required: false
