name: "Spike Story"
description: "驻住 拽专 , 拽转 转转,  转 驻转专转"
type: "Spike Story"

body:
  - type: textarea
    id: spike_question
    attributes:
      label: "砖 专转"
      description: |
        <div dir="rtl">
         砖 注拽专转 砖住驻拽   注转 注?
        </div>
      value: |
        <div dir="rtl">
        
    

        </div>
    validations:
      required: false


  - type: textarea
    id: outcome
    attributes:
      label: "转爪 专爪"
      description: |
        <div dir="rtl">
         转爪专 住驻 砖 住驻拽?  注专  拽 ?
        </div>
      value: |
        <div dir="rtl">

        
        </div>
    validations:
      required: false