name: "Spike Story"
description: "驻住 拽专 , 拽转 转转,  转 驻转专转"
type: "Spike Story"

body:
  - type: textarea
    id: spike_question
    attributes:
      label: "砖 专转"
      description: |
        <div dir="rtl">
         砖 注拽专转 砖住驻拽   注转 注?
        </div>

      placeholder: ":   砖转砖 -GraphQL 拽 REST API 驻专拽 砖 砖?"
      value: |
        <div dir="rtl">
        
    

        </div>
    validations:
      required: false


  - type: textarea
    id: outcome
    attributes:
      label: "转爪 专爪"
      description: |
        <div dir="rtl">
         转爪专 住驻 砖 住驻拽?  注专  拽 ?
        </div>
      placeholder: ": 住 住 注 爪 拽转, 转 拽 注转, 专转 专拽专."
    validations:
      required: false