name: "Task З"
description: "驻住 爪专转 砖 转  驻专 注"
type: "Task З"

body:
  - type: textarea
    id: task_description
    attributes:
      label: "转专 砖"
      description: |
        <div dir="rtl">
        转专 驻专  爪专 注砖转,  专拽注   专砖.
        </div>
      value: |
        <!-- For hebrew content use this template:
        <div dir="rtl">
        
        
        </div>
        -->
    validations:
      required: false
