name: "Bug "
description: "驻住 驻砖  注 转拽  注 注专转"
type: "Bug "

body:
  - type: textarea
    id: summary
    attributes:
      label: " 注?"
      description: |
        <div dir="rtl">
        ": 驻转专 砖专  注"
        </div>
      value: |
        <div dir="auto">
        
        </div>
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "爪 住"
      description: |
        <div dir="rtl">
        "  - 驻砖专 爪专祝    转专"
        </div>
      value: |
        <div dir="auto">
        
        </div>
    validations:
      required: false
