name: "Tech Debt ⚙️"
description: "טופס לתיעוד, מעקב וטיפול בחוב טכני במערכת"
type: "Tech Debt ⚙️"

body:
  - type: textarea
    id: debt_description
    attributes:
      label: "תיאור החוב הטכני"
      description: |
        <div dir="rtl">
        תאר את החוב הטכני, היכן הוא נמצא בקוד, ומדוע הוא נוצר.
        </div>
      value: |
        <!-- For hebrew content use this template:
        <div dir="rtl">
        
        
        </div>
        -->
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: "פתרון מוצע"
      description: |
        <div dir="rtl">
        תאר את הדרך המומלצת לטפל בחוב הטכני.
        </div>
      value: |
        <!-- For hebrew content use this template:
        <div dir="rtl">
        
        
        </div>
        -->
    validations:
      required: false