name: "Training "
description: "驻住 转  砖 专, 住,  驻砖 注"
type: "Training "

body:
  - type: textarea
    id: training_topic
    attributes:
      label: "砖 专"
      description: |
        <div dir="rtl">
        " 砖 专 砖 专?"
        </div>
      value: |
        <div dir="auto">


        
        </div>
      required: false