name: "Design "
description: "驻住 砖转 注爪 转"
type: "Design "

body:
  - type: textarea
    id: design_goal
    attributes:
      label: "专转 注爪"
      description: " 专 注拽专转 砖 砖转 注爪 ?  注 砖 住 驻转专?"
      placeholder: ": 注爪 祝 转 砖, 砖驻专 转 砖转砖 转 专砖..."
    validations:
      required: false