name: "Docs "
description: "驻住 转  注 砖 转注   驻"
type: "Docs "

body:
  - type: input
    id: doc_subject
    attributes:
      label: "砖 转注"
      description: " 砖 专 砖 转注 砖砖 转  注?"
      placeholder: ":  专 住转 驻转, 住专 注 API 砖..."
    validations:
      required: true