name: "Epic "
description: "驻住 爪专转 驻拽 (Epic) -   专转 住驻专 砖转"
title: "[Epic]: "
type: Epic 

body:
  - type: textarea
    id: epic_description
    attributes:
      label: "转专 驻拽"
      description: "转专 驻专 砖 注 注专 砖驻拽 "
      placeholder: "转专  驻拽 , 注  砖  注专 注住拽 砖"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "拽专专 砖"
      description: " 爪专 转拽  住 转 驻拽 砖"
      placeholder: |
        -  转转 住住转 砖转
        - 拽转 注专 爪
        - 转注 砖
    validations:
      required: true
