name: "Release "
description: "爪'拽住 转 爪 砖 专住 砖 驻专拽砖"
title: "Release v"
type: "Release "

body:
  - type: textarea
    id: pre_release_checklist
    attributes:
      label: "爪'拽住 驻 砖专专"
      description: "砖转 砖砖 爪注 驻 注转 专住."
      value: |
        - [ ]  砖转 专住 注专 QA 住专.
        - [ ] 爪注 拽转 专专住 转 注 住转 -Staging.
        - [ ] 拽抓 -CHANGELOG 注.
        - [ ] 爪专 转 (tag) -Git 注专 专住.
        - [ ] 转拽 砖专 住驻 砖专专.
    validations:
      required: true

  - type: textarea
    id: post_release_checklist
    attributes:
      label: "爪'拽住 专 砖专专"
      description: "砖转 砖砖 爪注 专 砖专住 注转 专."
      value: |
        - [ ] 专住 注转 爪 驻专拽砖.
        - [ ] 爪注 专   转拽转 注专转.
        - [ ] 砖 注 注 注 注 砖专专 专住.