name: "Release "
description: "爪'拽住 转 爪 砖 专住 砖 驻专拽砖"
title: "Release v"
type: "Release "

body:
  - type: textarea
    id: pre_release_checklist
    attributes:
      label: "爪'拽住 驻 砖专专"
      description: "砖转 砖砖 爪注 驻 注转 专住."
      value: |
        - [ ] All tasks in the release have passed QA and are closed.
        - [ ] Full regression testing has been completed on the staging environment.
        - [ ] A Git tag has been created for the release.
        - [ ] The CHANGELOG appear in the new release created.
        - [ ] Final approval for release has been received.
    validations:
      required: true

  - type: textarea
    id: post_release_checklist
    attributes:
      label: "爪'拽住 专 砖专专"
      description: "砖转 砖砖 爪注 专 砖专住 注转 专."
      value: |
        - [ ] The release has been successfully deployed to production.
        - [ ] System logs have been monitored and system health is confirmed.
        - [ ] Stakeholders have been notified of the new release.