name: "Spike "
description: "驻住 拽专 , 拽转 转转,  转 驻转专转"
type: "Spike "

body:
  - type: textarea
    id: spike_question
    attributes:
      label: "砖 专转"
      description: " 砖 注拽专转 砖住驻拽   注转 注?"
      placeholder: ":  专  转专 砖 驻砖  转?   砖转砖 住驻专 X  Y?"
    validations:
      required: true

  - type: textarea
    id: investigation_plan
    attributes:
      label: "转转 拽专"
      description: " 砖  砖 砖砖 拽专  注转 注 砖?"
      placeholder: |
        - 拽专 注 住驻专转 A, B, C.
        - 转 Proof of Concept (POC) 拽 注 驻转专 注祝.
        - 住 转专转 住专转 砖  砖.
    validations:
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: "转爪 专爪"
      description: " 转爪专 住驻 砖 住驻拽?  注专  拽 ?"
      placeholder: ": 住 住 注 爪 拽转, 转 拽 注转, 专转 专拽专."
    validations:
      required: true

  - type: textarea
    id: findings
    attributes:
      label: "爪 ( 住)"
      description: "住 住驻拽, 砖 住  转 爪, 住拽转, 爪 砖."