name: "Task З"
description: "驻住 爪专转 砖 转  驻专 注"
type: "Task З"

body:
  - type: textarea
    id: task_description
    attributes:
      label: "转专 砖"
      description: "转专 驻专  爪专 注砖转,  专拽注   专砖."
      placeholder: ": 砖专 住驻专转 React 专住 18, 爪专转 拽住 砖 住 转..."
    validations:
      required: true
