name: "Task 🧩"
description: "טופס ליצירת משימה טכנית או פריט עבודה"
type: "Task 🧩"

body:
  - type: textarea
    id: task_description
    attributes:
      label: "תיאור המשימה"
      description: |
        <div dir="rtl">
        תאר בפירוט מה צריך לעשות, כולל רקע טכני אם נדרש.
        </div>
      value: |
        <div dir="rtl">
        
        
        </div>
    validations:
      required: false
