name: "Test ✔️"
description: "טופס ליצירת תוכנית בדיקות או ביצוע בדיקות ידניות"
type: "Test ✔️"

body:
  - type: textarea
    id: test_plan
    attributes:
      label: "תרחישי בדיקה (Test Cases)"
      description: "פרט את תרחישי הבדיקה שיש לבצע. השתמש ברשימת תיוג."
      placeholder: |
        - [ ] בדיקת הרשמה עם אימייל תקין
        - [ ] בדיקת הרשמה עם אימייל לא תקין
        - [ ] בדיקת הרשמה עם סיסמה חלשה
        - [ ] בדיקת הרשמה עם שדות ריקים
    validations:
      required: true


  - type: textarea
    id: results
    attributes:
      label: "תוצאות (ימולא בסיום)"
      description: "סכם את תוצאות הבדיקה, כולל קישורים לבאגים שנפתחו."