name: "Training "
description: "驻住 转  砖 专, 住,  驻砖 注"
type: "Training "

body:
  - type: textarea
    id: training_topic
    attributes:
      label: "砖 专"
      description: " 砖 专 砖 专?"
      placeholder: ": 砖砖 -GitHub Actions, 注拽专转 SOLID, 专转 注 注专转 砖"
    validations:
      required: true